### ISSUE TITLE
internal reference doesn't work on pages

### ISSUE THREAD

**Issue by Yuancheng-Xu** [SUSTech-Application/2020-Fall#14]
在github repo里面打开md文件preview的话internal ref可以用（比如在我的分享里面点击 “我的申请”就可以跳到那一节）； 但是从主网页打开的page不能用：https://sustech-application.github.io/2020-Fall/#/grad-application/math/applied-mathematics/[US]-16-xuyuancheng

**Comment by dizzam** [comment]
按照Markdown的语法，cross ref写成类似

```markdown
[我的申请](#我的申请)
......
## 我的申请
```

是比较稳妥的，其它的写法可能兼容性上有差别。

**Comment by Yuancheng-Xu** [comment]
> 
> 
> 按照Markdown的语法，cross ref写成类似
> 
> ```gfm
> [我的申请](#我的申请)
> ......
> ## 我的申请
> ```
> 
> 是比较稳妥的，其它的写法可能兼容性上有差别。

这种写法好像标题里面不能有英文字母...

**Comment by dizzam** [comment]
我在[自己的 page](https://dizzam.github.io/2020-Fall/#/grad-application/math/applied-mathematics/[US]-16-xuyuancheng?id=%E5%BD%B1%E5%93%8Dphd%E7%94%B3%E8%AF%B7%E7%9A%84%E5%9B%A0%E7%B4%A0)上测试了一下，貌似没有什么问题。环境是chrome 81。

如果中英文混输的时候，里面有空格的话，要用短横代替

```markdown
[怎样提高英语与GPA](#英语与-GPA)
.......
## 英语与␣GPA
```

**Comment by Yuancheng-Xu** [comment]
> 
> 
> 我在[自己的 page](https://dizzam.github.io/2020-Fall/#/grad-application/math/applied-mathematics/%5BUS%5D-16-xuyuancheng?id=%E5%BD%B1%E5%93%8Dphd%E7%94%B3%E8%AF%B7%E7%9A%84%E5%9B%A0%E7%B4%A0)上测试了一下，貌似没有什么问题。环境是chrome 81。
> 
> 如果中英文混输的时候，里面有空格的话，要用短横代替
> 
> ```gfm
> [怎样提高英语与GPA](#英语与-GPA)
> .......
> ## 英语与␣GPA
> ```

以解决 谢谢Zeyu
